package GUI;

import DAO.ProdutoDAO;
import MODEL.Produto;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lulu
 */
public class GUIListarQuantidade extends javax.swing.JFrame {

    /**
     * Creates new form GUIListarQuantidade
     */
    public GUIListarQuantidade() {
        initComponents();
        listaProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaProdutoQuantidade = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarProdutos = new javax.swing.JMenuItem();
        CadastrarCategoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        listarNome = new javax.swing.JMenuItem();
        listarQuantidade = new javax.swing.JMenuItem();
        listarMaiorQuantidade = new javax.swing.JMenuItem();
        listarCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        deletarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaProdutoQuantidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Quantidade", "Nome", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutoQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoQuantidadeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaProdutoQuantidade);

        jMenu1.setText("Cadastrar");

        CadastrarProdutos.setText("Produtos");
        CadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarProdutos);

        CadastrarCategoria.setText("Categorias");
        CadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarCategoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        listarNome.setText("Prod. por nome");
        listarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarNomeActionPerformed(evt);
            }
        });
        jMenu2.add(listarNome);

        listarQuantidade.setText("Prod. por quantidade");
        listarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarQuantidadeActionPerformed(evt);
            }
        });
        jMenu2.add(listarQuantidade);

        listarMaiorQuantidade.setText("Maior/Menor quantidade");
        listarMaiorQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMaiorQuantidadeActionPerformed(evt);
            }
        });
        jMenu2.add(listarMaiorQuantidade);

        listarCategoria.setText("Por categoria");
        listarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(listarCategoria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Deletar");

        deletarProduto.setText("Produtos");
        deletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(deletarProduto);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutoQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoQuantidadeMouseClicked

    }//GEN-LAST:event_tabelaProdutoQuantidadeMouseClicked

    private void CadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutosActionPerformed
        GUICadastroProduto janela = null;
        try {
            janela = new GUICadastroProduto();
        } catch (SQLException ex) {
            
        }
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadastrarProdutosActionPerformed

    private void CadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarCategoriaActionPerformed
        GUICadastrarCategoria janela = new GUICadastrarCategoria();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadastrarCategoriaActionPerformed

    private void listarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarNomeActionPerformed
        GUIListarNome janela = new GUIListarNome();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listarNomeActionPerformed

    private void listarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarQuantidadeActionPerformed
        GUIListarQuantidade janela = new GUIListarQuantidade();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listarQuantidadeActionPerformed

    private void listarMaiorQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMaiorQuantidadeActionPerformed
        GUIListarMaiorMenorQuantidade janela = new GUIListarMaiorMenorQuantidade();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listarMaiorQuantidadeActionPerformed

    private void listarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCategoriaActionPerformed
        GUIListarCategoria janela = null;
        try {
            janela = new GUIListarCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(GUIListarQuantidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listarCategoriaActionPerformed

    private void deletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarProdutoActionPerformed
        GUIDeletarProduto janela = new GUIDeletarProduto();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deletarProdutoActionPerformed
    public void listaProdutos(){
        try{
            List <Produto> produtos = ProdutoDAO.buscarProduto("quantidade"); 
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutoQuantidade.getModel(); 
            modelo.setNumRows(0);
            for(Produto produto: produtos){ 
                modelo.addRow(new Object[]{ 
                    produto.getQuantidade(),
                    produto.getNome(),
                    ProdutoDAO.recuperarNome(produto.getId_categoria())
                });
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Problema na busca do Produto");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarQuantidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarQuantidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarQuantidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarQuantidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarQuantidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarCategoria;
    private javax.swing.JMenuItem CadastrarProdutos;
    private javax.swing.JMenuItem deletarProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem listarCategoria;
    private javax.swing.JMenuItem listarMaiorQuantidade;
    private javax.swing.JMenuItem listarNome;
    private javax.swing.JMenuItem listarQuantidade;
    private javax.swing.JTable tabelaProdutoQuantidade;
    // End of variables declaration//GEN-END:variables
}
